- name: Install Koji web packages
  package:
    name: koji-web
    state: present

- name: copy /etc/httpd/conf.d/kojiweb.conf
  copy:
    src: files/kojiweb.conf
    dest: /etc/httpd/conf.d/kojiweb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: copy /etc/kojiweb/web.conf
  copy:
    src: files/web.conf
    dest: /etc/kojiweb/web.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: grant apache selinux access to kojiweb keytab
  sefcontext:
    target: /var/local/koji.kojiweb.keytab
    setype: httpd_config_t
    state: present
  when:
    - ansible_selinux.status != "disabled"
  notify:
    - restart httpd

- name: grant apache read access to kojiweb keytab
  file:
    path: /var/local/koji.kojiweb.keytab
    owner: root
    group: apache
    mode: 0640
    setype: httpd_config_t
  notify:
    - restart httpd

- name: allow httpd selinux access to contact kerberos and koji-hub
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when:
    - ansible_selinux.status != "disabled"
  notify:
    - restart httpd

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: disable_selinux

- name: Create symbolic link to koji-web dev folder
  file:
    src: /opt/koji/www
    dest: /usr/share/koji-web-develop
    state: link
  when: dev_env

- name: Create symbolic link to koji-web scripts
  file:
    src: /opt/koji/www/kojiweb
    dest: /opt/koji/www/scripts
    state: link
  when: dev_env

- name: Change root folder in kojiweb.conf
  replace:
    path: /etc/httpd/conf.d/kojiweb.conf
    regexp: '/usr/share/koji-web'
    replace: '/usr/share/koji-web-develop'
  when: dev_env

- name: Change root folder in web.conf
  replace:
    path: /etc/kojiweb/web.conf
    regexp: '/usr/share/koji-web'
    replace: '/usr/share/koji-web-develop'
  notify:
    - restart httpd
  when: dev_env
