# -*- mode: ruby -*-

### configuration parameters ###
ENV['DEV_ENV_PATH'] = '/home/mkulik/Downloads/koji-test'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  if ENV['DEV_ENV_PATH'] != ''
    config.vm.box = "fedora/36-cloud-base"
    config.vm.synced_folder ENV['DEV_ENV_PATH'], "/opt/koji", type: "nfs", nfs_udp: false
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8043
  else
    config.vm.box = "centos/stream8"
  end
  config.vm.box_check_update = false

  config.vm.provision "ansible" do |ansible|
    if ENV['DEV_ENV_PATH'] != ''
      ansible.playbook = "vagrant-dev-env.yml"
    else
      ansible.playbook = "vagrant.yml"
    end
  end

  config.vm.provider :libvirt do |virt|
    virt.storage :file, :size => '20G', :device => 'vdb'
    virt.memory = 4096
    virt.cpus = 2
    virt.qemu_use_session = false
  end

  config.ssh.forward_agent = true

  config.vm.define :kojidev do |node|
     node.vm.hostname = 'kojidev'
  end

  # This creates a second NIC, which I do not want:
  # config.vm.network :private_network, :ip => '192.168.121.100'
  # Also there seems to be a bug with wrapping the network settings in a
  # "provider" block:
  # https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1165

end
