- name: Add yum repository to work around rhbz1661580
  yum_repository:
    name: bz1661580
    description: work around rhbz1661580
    baseurl: https://fedorapeople.org/~ktdreyer/bz1661580/
    gpgcheck: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Install the very latest requests-kerberos (rhbz1661580)
  package:
    name:
      - python-requests-kerberos
      - python2-kerberos
    state: latest  # noqa 403
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Install Koji builder packages
  package:
    name: koji-builder
    state: present

- name: copy /etc/kojid/kojid.conf
  copy:
    src: files/kojid.conf
    dest: /etc/kojid/kojid.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kojid

# Because we have "topurl=https://..." in kojid.conf, we must trust this CA
# system-wide because we query this URL with urllib2.

- name: link our Koji CA to the system-wide location
  file:
    src: /etc/pki/koji/koji-ca.crt
    dest: /etc/pki/ca-trust/source/anchors/koji-ca.crt
    state: link
  register: koji_ca_anchor

- name: trust our new Koji CA system-wide  # noqa 503
  command: update-ca-trust extract
  when: koji_ca_anchor.changed
  notify:
    - restart kojid

- name: Link dev kojid script
  file:
    src: /opt/koji/builder/kojid
    dest: /usr/sbin/kojid-dev
    state: link
  when: dev_env

- name: Replace kojid path in .service
  replace:
    path: /usr/lib/systemd/system/kojid.service
    regexp: '/usr/sbin/kojid'
    replace: '/usr/sbin/kojid-dev'
  when: dev_env

- name: Change py2 to py3 in kojid-dev
  replace:
    path: /usr/sbin/kojid-dev
    regexp: '/usr/bin/python2'
    replace: '/usr/bin/python3'
  when: dev_env

- name: Copy kojid restarter script
  copy:
    src: files/kojid-watcher.sh
    dest: /opt
    owner: root
    group: root
    mode: '770'
  when: dev_env

- name: Copy kojid restarter service
  copy:
    src: files/kojid-watcher.service
    dest: /etc/systemd/system
    owner: root
    group: root
  when: dev_env

- name: Reload systemd
  systemd:
    daemon_reexec: yes
  when: dev_env

- name: start kojid
  service:
    name: kojid
    enabled: true
    state: started

- name: start kojid restarter
  service:
    name: kojid-watcher.service
    enabled: true
    state: started
  when: dev_env
